name: Deploy to AWS

on:
  push:
    branches:
      - deploy  # Only triggers for the deploy branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init
        working-directory: .

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        working-directory: .
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}

      - name: Get backend URL
        id: get-backend-url
        run: |
          backend_url=$(terraform output -raw REACT_APP_BACKEND_SERVICE_URL | tr -d '\n')
          echo "REACT_APP_BACKEND_SERVICE_URL=http://${backend_url}" >> $GITHUB_ENV
        working-directory: .

      - name: Debug Backend URL
        run: |
          echo "Backend URL: $REACT_APP_BACKEND_SERVICE_URL"
        env:
          REACT_APP_BACKEND_SERVICE_URL: ${{ env.REACT_APP_BACKEND_SERVICE_URL }}

      - name: Get frontend URL
        id: get-frontend-url
        run: |
          frontend_url=$(terraform output -raw REACT_APP_API_SERVICE_URL | tr -d '\n')
          echo "REACT_APP_API_SERVICE_URL=http://${frontend_url}" >> $GITHUB_ENV
        working-directory: .

      - name: Debug Frontend URL
        run: |
          echo "Frontend URL: $REACT_APP_API_SERVICE_URL"
        env:
          REACT_APP_API_SERVICE_URL: ${{ env.REACT_APP_API_SERVICE_URL }}

      - name: Log in to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build, tag, and push Backend image
        env:
          REACT_APP_BACKEND_SERVICE_URL: ${{ env.REACT_APP_BACKEND_SERVICE_URL }}
          REDIS_HOST: "redis-19369.c11.us-east-1-3.ec2.redns.redis-cloud.com"
          REDIS_PORT: "19369"
          REDIS_PASSWORD: "iwIGMW4rywGlc4sNNA95UQcUBuC6auwW"
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          docker build --no-cache -f ./be/Dockerfile -t backend:latest ./be
          docker tag backend:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/backend:latest
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/backend:latest

      - name: Build, tag, and push Frontend image
        env:
          REACT_APP_API_SERVICE_URL: ${{ env.REACT_APP_API_SERVICE_URL }}
          REACT_APP_BACKEND_SERVICE_URL: ${{ env.REACT_APP_BACKEND_SERVICE_URL }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          docker build --no-cache -f ./fe/Dockerfile -t frontend:latest --build-arg NODE_ENV=production --build-arg REACT_APP_BACKEND_SERVICE_URL=$REACT_APP_BACKEND_SERVICE_URL ./fe
          docker tag frontend:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/frontend:latest
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/frontend:latest
